# Generated by Django 2.1.7 on 2019-03-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('floors_walked', models.IntegerField(null=True)),
                ('calories_burned', models.IntegerField()),
                ('steps_taken', models.IntegerField(null=True)),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_author', to='customUsers.Profile')),
            ],
        ),
    ]
