# Generated by Django 2.1.7 on 2019-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
    ]
