# Generated by Django 2.1.7 on 2019-03-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntries', '0002_dataentry_week_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='benefitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_title', models.CharField(default='NONE', max_length=50)),
                ('benefit_text', models.TextField()),
            ],
        ),
    ]
