# Generated by Django 2.1.7 on 2019-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntries', '0003_benefitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitlist',
            name='benefit_title',
            field=models.CharField(default='NONE', max_length=50, null=True),
        ),
    ]
