# Generated by Django 2.1.7 on 2019-03-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntries', '0004_auto_20190325_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitlist',
            name='benefit_title',
        ),
    ]
