# Generated by Django 2.1.7 on 2019-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntries', '0005_remove_benefitlist_benefit_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='climateBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_title', models.CharField(max_length=100)),
                ('climate_text', models.TextField()),
            ],
        ),
    ]
