# Generated by Django 2.1.7 on 2019-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0002_auto_20190314_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalCaloriesBurned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalStairsStepped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalStepsTaken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
