# Generated by Django 2.1.7 on 2019-03-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0003_auto_20190314_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='totalCaloriesBurned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalStairsStepped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalStepsTaken',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
