# Generated by Django 2.1.7 on 2019-03-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0005_auto_20190314_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalEntries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
