# Generated by Django 2.1.7 on 2019-03-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(default='NONE', max_length=50)),
                ('announcement_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_auth', models.CharField(default='NONE', max_length=50)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('On-hold', 'On-hold')], default='Active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('On-hold', 'On-hold')], max_length=8)),
                ('ticket_desc', models.TextField()),
                ('ticket_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_customer', to='customUsers.Profile')),
                ('ticket_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tech', to='customUsers.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Tickets'),
        ),
    ]
